variables:
  TAG: latest
  DOCKER_DRIVER: overlay2

default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin

stages:
  - base
  - stage1
  - stage2

build_base_image:
  stage: base
  timeout: 6h
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - cd docker
    - docker buildx build
      --no-cache
      --platform "linux/amd64,linux/arm64"
      --tag "$CI_REGISTRY_IMAGE/px4-dev-base-image:latest"
      --file "Dockerfile_base"
      --push
      .
  rules:
    - changes:  
      - "docker/Dockerfile_base"
      when: manual

build_nuttx_image:
  stage: stage1
  timeout: 6h
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - cd docker
    - docker buildx build
      --no-cache
      --platform "linux/amd64"
      --tag "$CI_REGISTRY_IMAGE/px4-dev-nuttx-image:latest"
      --file "Dockerfile_nuttx"
      --push
      .
  rules:
    - changes:  
        - "docker/Dockerfile_base"
        - "docker/Dockerfile_nuttx"

build_simulation_image:
  stage: stage1
  timeout: 6h
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - cd docker
    - docker buildx build
      --no-cache
      --platform "linux/amd64"
      --tag "$CI_REGISTRY_IMAGE/px4-dev-simulation-image:latest"
      --file "Dockerfile_simulation"
      --push
      .
  rules:
    - changes:  
        - "docker/Dockerfile_base"
        - "docker/Dockerfile_simulation"

build_simulation_extra_image:
  stage: stage2
  timeout: 6h
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - cd docker
    - docker buildx build
      --no-cache
      --platform "linux/amd64"
      --tag "$CI_REGISTRY_IMAGE/px4-dev-simulation-extra-image:latest"
      --file "Dockerfile_simulation_extra"
      --push
      .
  rules:
    - changes:  
        - "docker/Dockerfile_base"
        - "docker/Dockerfile_simulation"
        - "docker/Dockerfile_simulation_extra"

build_ros2_bridge_base_image:
  stage: stage1
  timeout: 6h
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - cd docker
    - docker buildx build
      --no-cache
      --platform "linux/amd64,linux/arm64"
      --tag "$CI_REGISTRY_IMAGE/px4-dev-ros2-bridge-base-image:latest"
      --file "Dockerfile_px4_ros2_bridge_base"
      --push
      .
  rules:
    - changes:  
        - "docker/Dockerfile_base"
        - "docker/Dockerfile_px4_ros2_bridge_base"
      when: manual

build_ros2_bridge_image:
  stage: stage2
  timeout: 6h
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - cd docker
    - docker buildx build
      --no-cache
      --platform "linux/amd64,linux/arm64"
      --tag "$CI_REGISTRY_IMAGE/px4-dev-ros2-bridge-image:latest"
      --file "Dockerfile_px4_ros2_bridge"
      --push
      .
  rules:
    - changes:  
        - "docker/Dockerfile_base"
        - "docker/Dockerfile_px4_ros2_bridge_base"
        - "docker/Dockerfile_px4_ros2_bridge"

