/uav1/px4_ros_api:
  ros__parameters:
    system_id: 1
    buffer_rate: 50
    base_link_frame: "base_link_1"
    odometry_link_frame: "odom_1"
    publish_map_odom_tf: True
    map_link_frame: "map"
    map_to_odom_translation: [0.0, 0.0, 0.0]
    map_to_odom_rpy: [0.0, 0.0, 0.0]

/uav2/px4_ros_api:
  ros__parameters:
    system_id: 2
    buffer_rate: 50
    base_link_frame: "base_link_2"
    odometry_link_frame: "odom_2"
    publish_map_odom_tf: True
    map_link_frame: "map"
    map_to_odom_translation: [0.0, 3.0, 0.0]
    map_to_odom_rpy: [0.0, 0.0, 0.0]

/uav3/px4_ros_api:
  ros__parameters:
    system_id: 3
    buffer_rate: 50
    base_link_frame: "base_link_3"
    odometry_link_frame: "odom_3"
    publish_map_odom_tf: True
    map_link_frame: "map"
    map_to_odom_translation: [0.0, 6.0, 0.0]
    map_to_odom_rpy: [0.0, 0.0, 0.0]