# Parameters for the px4_ros_api node
/uav1/px4_ros_api:
  ros__parameters:
    # System ID
    system_id: 1
    # Buffer rate
    buffer_rate: 50
    # Base link frame
    base_link_frame: "base_link_1"
    # Odometry link frame
    odometry_link_frame: "odom_1"
    # Publish map -> odom tf
    publish_map_odom_tf: True
    # Map link frame
    map_link_frame: "map"
    # Translation between "map" and "odom" frames (ENU)
    map_to_odom_translation: [1.0, 1.0, 0.0]
    # Roll, pitch, and yaw angles for the transformation between "map" and "odom" frames (ENU)
    map_to_odom_rpy: [0.0, 0.0, 0.0]
    # Subscribe to external odometry (i.e., visual odometry). If True, subscribe_to_pose must be set to False.
    subscribe_to_external_odometry: False
    # Subscribe to external pose (i.e., MoCap pose). If True, subscribe_to_odometry must be set to False.
    subscribe_to_external_pose: False
