FROM registry.gitlab.com/ant-x/tools/docker-px4/px4-dev-base-image:latest

ENV DEBIAN_FRONTEND noninteractive

ENV ROS_DISTRO foxy

# Ensure that the Ubuntu Universe repository is enabled
RUN add-apt-repository universe

# Add the ROS 2 GPG key with apt
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

# Add the repository to your sources list
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Install ROS2 desktop
RUN apt-get update && apt-get install -y --no-install-recommends \
        ros-$ROS_DISTRO-desktop \
        ros-$ROS_DISTRO-tf2-geometry-msgs \
        ros-$ROS_DISTRO-eigen3-cmake-module \
        ros-$ROS_DISTRO-rmw-fastrtps-cpp \
        ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
        ros-dev-tools

# Select RMW implementation
ENV RMW_IMPLEMENTATION rmw_fastrtps_cpp

# Install development tools and ROS tools
RUN apt-get update && apt-get install -y \
        python3-argcomplete \
        python3-colcon-common-extensions \
        python3-genmsg
RUN pip3 install pyros-genmsg empy==3.3.4 setuptools==58.2.0

## Install PX4-ROS2 Bridge ##
WORKDIR /root/px4_ros_com_ros2/src
RUN git clone https://github.com/PX4/px4_ros_com.git -b release/1.13
RUN git clone https://github.com/PX4/px4_msgs.git -b release/1.13
WORKDIR /root/px4_ros_com_ros2
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && colcon build"

# Source colcon environment
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" | tee -a /etc/bash.bashrc /etc/profile
RUN echo "source /root/px4_ros_com_ros2/install/setup.bash" | tee -a /etc/bash.bashrc /etc/profile ~/.bashrc

# Setup colcon_cd
RUN echo "source /usr/share/colcon_cd/function/colcon_cd.sh" | tee -a /etc/bash.bashrc /etc/profile
RUN echo "export _colcon_cd_root=/opt/ros/$ROS_DISTRO/" | tee -a /etc/bash.bashrc /etc/profile

# Setup colcon tab completition
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" | tee -a /etc/bash.bashrc /etc/profile

WORKDIR /root/px4_ros_com_ros2

CMD ["bash"]
