FROM registry.gitlab.com/ant-x/tools/docker-px4/px4-dev-ros2-bridge-base-image:latest

ENV DEBIAN_FRONTEND noninteractive

ENV ROS_DISTRO foxy

# Install px4_ros_extra and px4_ros_api
WORKDIR /root/px4_ros_com_ros2/src
RUN git clone https://gitlab.com/ant-x/tools/px4_ros_extra.git
RUN git clone https://gitlab.com/ant-x/tools/px4_ros_api.git
WORKDIR /root/px4_ros_com_ros2
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && source /root/px4_ros_com_ros2/install/setup.bash && \
    colcon build --symlink-install --packages-select px4_ros_extra px4_ros_api"

WORKDIR /root/px4_ros_com_ros2

CMD ["bash"]
